// <auto-generated />
using System;
using DevHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHub.Migrations
{
    [DbContext(typeof(ItrecruitmentDbContext))]
    [Migration("20260616042906_AddPreferredWorkingModel")]
    partial class AddPreferredWorkingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevHub.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("AdminId")
                        .HasName("PK__admin__43AA41418C23432B");

                    b.HasIndex(new[] { "Username" }, "UQ__admin__F3DBC5727CFAE85F")
                        .IsUnique();

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cover_letter");

                    b.Property<int>("CvId")
                        .HasColumnType("int")
                        .HasColumnName("cv_id");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("ApplicationId")
                        .HasName("PK__applicat__3BCBDCF26F68278F");

                    b.HasIndex("CvId");

                    b.HasIndex(new[] { "CandidateId" }, "idx_application_candidate");

                    b.HasIndex(new[] { "JobId" }, "idx_application_job");

                    b.ToTable("application", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_type");

                    b.HasKey("LogId")
                        .HasName("PK__audit_lo__9E2397E0562E6B47");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("blog_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("author");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("published_at");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("BlogId")
                        .HasName("PK__blog_pos__2975AA28BA813DA3");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.HasIndex(new[] { "Slug" }, "UQ__blog_pos__32DD1E4C47481A2E")
                        .IsUnique();

                    b.ToTable("blog_post", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookmark_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookmarkId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.HasKey("BookmarkId")
                        .HasName("PK__bookmark__D9C65802FC133ABD");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId");

                    b.ToTable("bookmark", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<bool?>("CvSearchable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("cv_searchable");

                    b.Property<decimal?>("ExpectedSalaryMax")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("expected_salary_max");

                    b.Property<decimal?>("ExpectedSalaryMin")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("expected_salary_min");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("preferred_location");

                    b.Property<string>("PreferredWorkingModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("preferred_working_model");

                    b.Property<int?>("ProfileCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("profile_completion");

                    b.Property<string>("SocialMediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("social_media_url");

                    b.HasKey("CandidateId")
                        .HasName("PK__candidat__39BD4C187D159B41");

                    b.ToTable("candidate", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<int>("TechId")
                        .HasColumnType("int")
                        .HasColumnName("tech_id");

                    b.Property<string>("Level")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("level");

                    b.HasKey("CandidateId", "TechId")
                        .HasName("PK__candidat__87B0340FA344E306");

                    b.HasIndex("TechId");

                    b.ToTable("candidate_skill", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.CommonJobPosition", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("position_name");

                    b.HasKey("PositionId")
                        .HasName("PK__common_j__99A0E7A487B920C3");

                    b.HasIndex(new[] { "PositionName" }, "UQ__common_j__0030EAD7A7C738AF")
                        .IsUnique();

                    b.ToTable("common_job_position", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.CommonTechnology", b =>
                {
                    b.Property<int>("TechId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tech_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("TechName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tech_name");

                    b.HasKey("TechId")
                        .HasName("PK__common_t__E0D7817A3C28CA0C");

                    b.HasIndex(new[] { "TechName" }, "UQ__common_t__AC1EA1F13AC03AE9")
                        .IsUnique();

                    b.ToTable("common_technology", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Cv", b =>
                {
                    b.Property<int>("CvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cv_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CvId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cv_url");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("education");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("experience");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("languages");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("skills");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CvId")
                        .HasName("PK__cv__C36883E6D4E21DAA");

                    b.HasIndex("CandidateId");

                    b.ToTable("cv", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("interview_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("application_id");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("meeting_link");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("scheduled")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("InterviewId")
                        .HasName("PK__intervie__141E55525829E99E");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("interview", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.JobPost", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int?>("ApplicationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("application_count");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("approved_at");

                    b.Property<string>("Benefit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("benefit");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("experience_level");

                    b.Property<int?>("HiringQuota")
                        .HasColumnType("int")
                        .HasColumnName("hiring_quota");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("int")
                        .HasColumnName("moderator_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<int?>("PriorityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("priority_score");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<int>("CompanyPackageHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_package_history_id");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("Requirement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirement");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salary_min");

                    b.Property<string>("Skill")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("skill");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("WorkingModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("working_model");

                    b.HasKey("JobId")
                        .HasName("PK__job_post__6E32B6A56D928E5F");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("PositionId");

                    b.HasIndex("CompanyPackageHistoryId");

                    b.HasIndex(new[] { "RecruiterId" }, "idx_job_post_recruiter");

                    b.HasIndex(new[] { "Status" }, "idx_job_post_status");

                    b.ToTable("job_post", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reference_type");

                    b.Property<string>("SeverityLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Low")
                        .HasColumnName("severity_level");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_type");

                    b.HasKey("NotificationId")
                        .HasName("PK__notifica__E059842F06EAA605");

                    b.HasIndex(new[] { "UserId", "UserType" }, "idx_notification_user");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.PackageTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("AmountVnd")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount_vnd");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("final_amount");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("vnpay")
                        .HasColumnName("payment_method");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("transaction_type");

                    b.Property<string>("VnpayBankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vnpay_bank_code");

                    b.Property<string>("VnpayTransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vnpay_transaction_no");

                    b.Property<string>("VnpayTxnRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vnpay_txn_ref");

                    b.HasKey("TransactionId")
                        .HasName("PK__package___85C600AFBBD9338E");

                    b.HasIndex("PromotionId");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("ServiceId");

                    b.ToTable("package_transaction", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discount_percent");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("max_discount");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("promo_code");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("PromotionId")
                        .HasName("PK__promotio__2CB9556B27C78245");

                    b.HasIndex(new[] { "PromoCode" }, "UQ__promotio__C07E23151D5A3120")
                        .IsUnique();

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Recruiter", b =>
                {
                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("AdditionalDocumentsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("additional_documents_url");

                    b.Property<decimal?>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("average_rating");

                    b.Property<string>("BusinessLicenseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("business_license_url");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_address");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_description");

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("company_logo_url");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("industry");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position");

                    b.Property<int?>("ProfileCompletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("profile_completion");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tax_code");

                    b.Property<int?>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_reviews");

                    b.Property<decimal?>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_spent");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("website");

                    b.HasKey("RecruiterId")
                        .HasName("PK__recruite__42ABA2576945C9D7");

                    b.ToTable("recruiter", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.CompanyPackageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("PostsGranted")
                        .HasColumnType("int")
                        .HasColumnName("posts_granted");

                    b.Property<int>("PostsRemaining")
                        .HasColumnType("int")
                        .HasColumnName("posts_remaining");

                    b.Property<decimal>("PriceAtPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price_at_purchase");

                    b.Property<int>("PromotionsRemaining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("promotions_remaining");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("PK__recruite__3213E83FA34D72CF");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("recruiter_package_history", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.ReviewCompany", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("candidate_id");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cons");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_anonymous");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("moderated_at");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("int")
                        .HasColumnName("moderator_id");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pros");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ReviewId")
                        .HasName("PK__review_r__60883D90CFCBFACD");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("RecruiterId");

                    b.HasIndex(new[] { "CandidateId", "RecruiterId" }, "UQ_candidate_recruiter_review")
                        .IsUnique();

                    b.ToTable("review_recruiter", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.ServicePackage", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Credit")
                        .HasColumnType("int")
                        .HasColumnName("credit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<bool?>("HasAiChatbot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("has_ai_chatbot");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxPosts")
                        .HasColumnType("int")
                        .HasColumnName("max_posts");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("package_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("PriorityPush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("priority_push");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ServiceId")
                        .HasName("PK__service___3E0DB8AF78E35848");

                    b.ToTable("service_package", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("google_id");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("otp_expires_at");

                    b.Property<string>("OtpVerification")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("otp_verification");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("ResetPasswordExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reset_password_expires_at");

                    b.Property<string>("ResetPassworvmken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reset_password_token");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_type");

                    b.HasKey("UserId")
                        .HasName("PK__user_acc__B9BE370FB27D0E4F");

                    b.HasIndex(new[] { "Email" }, "UQ__user_acc__AB6E6164EFF0C5ED")
                        .IsUnique();

                    b.HasIndex(new[] { "GoogleId" }, "UQ_user_google_id")
                        .IsUnique()
                        .HasFilter("([google_id] IS NOT NULL)");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("JobTechStack", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("TechId")
                        .HasColumnType("int")
                        .HasColumnName("tech_id");

                    b.HasKey("JobId", "TechId")
                        .HasName("PK__job_tech__D03FCEB2D9718A37");

                    b.HasIndex(new[] { "TechId", "JobId" }, "idx_job_tech_stack_lookup");

                    b.ToTable("job_tech_stack", (string)null);
                });

            modelBuilder.Entity("DevHub.Models.Admin", b =>
                {
                    b.HasOne("DevHub.Models.UserAccount", "AdminNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("DevHub.Models.Admin", "AdminId")
                        .IsRequired()
                        .HasConstraintName("FK__admin__admin_id__571DF1D5");

                    b.Navigation("AdminNavigation");
                });

            modelBuilder.Entity("DevHub.Models.Application", b =>
                {
                    b.HasOne("DevHub.Models.Candidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__applicati__candi__73BA3083");

                    b.HasOne("DevHub.Models.Cv", "Cv")
                        .WithMany("Applications")
                        .HasForeignKey("CvId")
                        .IsRequired()
                        .HasConstraintName("FK__applicati__cv_id__74AE54BC");

                    b.HasOne("DevHub.Models.JobPost", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__applicati__job_i__75A278F5");

                    b.Navigation("Candidate");

                    b.Navigation("Cv");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DevHub.Models.BlogPost", b =>
                {
                    b.HasOne("DevHub.Models.Recruiter", "AuthorRecruiter")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevHub.Models.Admin", "Publisher")
                        .WithMany("BlogPosts")
                        .HasForeignKey("PublisherId")
                        .IsRequired()
                        .HasConstraintName("FK__blog_post__publi__395884C4");

                    b.Navigation("AuthorRecruiter");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DevHub.Models.Bookmark", b =>
                {
                    b.HasOne("DevHub.Models.Candidate", "Candidate")
                        .WithMany("Bookmarks")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__bookmark__candid__32AB8735");

                    b.HasOne("DevHub.Models.JobPost", "Job")
                        .WithMany("Bookmarks")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK__bookmark__job_id__339FAB6E");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DevHub.Models.Candidate", b =>
                {
                    b.HasOne("DevHub.Models.UserAccount", "CandidateNavigation")
                        .WithOne("Candidate")
                        .HasForeignKey("DevHub.Models.Candidate", "CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__candidate__candi__49C3F6B7");

                    b.Navigation("CandidateNavigation");
                });

            modelBuilder.Entity("DevHub.Models.CandidateSkill", b =>
                {
                    b.HasOne("DevHub.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__candidate__candi__68487DD7");

                    b.HasOne("DevHub.Models.CommonTechnology", "Tech")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("TechId")
                        .IsRequired()
                        .HasConstraintName("FK__candidate__tech___693CA210");

                    b.Navigation("Candidate");

                    b.Navigation("Tech");
                });

            modelBuilder.Entity("DevHub.Models.Cv", b =>
                {
                    b.HasOne("DevHub.Models.Candidate", "Candidate")
                        .WithMany("Cvs")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__cv__candidate_id__6EF57B66");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("DevHub.Models.Interview", b =>
                {
                    b.HasOne("DevHub.Models.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK__interview__appli__7C4F7684");

                    b.HasOne("DevHub.Models.Candidate", "Candidate")
                        .WithMany("Interviews")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__interview__candi__7E37BEF6");

                    b.HasOne("DevHub.Models.Recruiter", "Recruiter")
                        .WithMany("Interviews")
                        .HasForeignKey("RecruiterId")
                        .IsRequired()
                        .HasConstraintName("FK__interview__recru__7D439ABD");

                    b.Navigation("Application");

                    b.Navigation("Candidate");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("DevHub.Models.JobPost", b =>
                {
                    b.HasOne("DevHub.Models.Admin", "Moderator")
                        .WithMany("JobPosts")
                        .HasForeignKey("ModeratorId")
                        .HasConstraintName("FK__job_post__modera__619B8048");

                    b.HasOne("DevHub.Models.CommonJobPosition", "Position")
                        .WithMany("JobPosts")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK__job_post__positi__60A75C0F");

                    b.HasOne("DevHub.Models.Recruiter", "Recruiter")
                        .WithMany()
                        .HasForeignKey("RecruiterId")
                        .IsRequired()
                        .HasConstraintName("FK__job_post__recruiter");

                    b.HasOne("DevHub.Models.CompanyPackageHistory", "CompanyPackageHistory")
                        .WithMany("JobPosts")
                        .HasForeignKey("CompanyPackageHistoryId")
                        .IsRequired()
                        .HasConstraintName("FK__job_post__package_history");

                    b.Navigation("Moderator");

                    b.Navigation("Position");

                    b.Navigation("Recruiter");

                    b.Navigation("CompanyPackageHistory");
                });

            modelBuilder.Entity("DevHub.Models.PackageTransaction", b =>
                {
                    b.HasOne("DevHub.Models.Promotion", "Promotion")
                        .WithMany("PackageTransactions")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__package_transaction__promotion");

                    b.HasOne("DevHub.Models.Recruiter", "Recruiter")
                        .WithMany("PackageTransactions")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__package_transaction__recruiter");

                    b.HasOne("DevHub.Models.ServicePackage", "Service")
                        .WithMany("PackageTransactions")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__package_transaction__service");

                    b.Navigation("Promotion");

                    b.Navigation("Recruiter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DevHub.Models.Recruiter", b =>
                {
                    b.HasOne("DevHub.Models.UserAccount", "RecruiterNavigation")
                        .WithOne("Recruiter")
                        .HasForeignKey("DevHub.Models.Recruiter", "RecruiterId")
                        .IsRequired()
                        .HasConstraintName("FK__recruiter__recru__534D60F1");

                    b.Navigation("RecruiterNavigation");
                });

            modelBuilder.Entity("DevHub.Models.CompanyPackageHistory", b =>
                {
                    b.HasOne("DevHub.Models.Recruiter", "Recruiter")
                        .WithMany("CompanyPackageHistories")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__recruiter_history__recruiter");

                    b.HasOne("DevHub.Models.ServicePackage", "Service")
                        .WithMany("CompanyPackageHistories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__recruiter_history__service");

                    b.HasOne("DevHub.Models.PackageTransaction", "Transaction")
                        .WithMany("CompanyPackageHistories")
                        .HasForeignKey("TransactionId")
                        .IsRequired()
                        .HasConstraintName("FK__recruiter_history__transaction");

                    b.Navigation("Recruiter");

                    b.Navigation("Service");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DevHub.Models.ReviewCompany", b =>
                {
                    b.HasOne("DevHub.Models.Candidate", "Candidate")
                        .WithMany("ReviewCompanies")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK__review_re__candi__2DE6D218");

                    b.HasOne("DevHub.Models.Admin", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId");

                    b.HasOne("DevHub.Models.Recruiter", "Recruiter")
                        .WithMany("ReviewCompanies")
                        .HasForeignKey("RecruiterId")
                        .IsRequired()
                        .HasConstraintName("FK__review_re__recru__2EDAF651");

                    b.Navigation("Candidate");

                    b.Navigation("Moderator");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("JobTechStack", b =>
                {
                    b.HasOne("DevHub.Models.JobPost", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__job_tech___job_i__6477ECF3");

                    b.HasOne("DevHub.Models.CommonTechnology", null)
                        .WithMany()
                        .HasForeignKey("TechId")
                        .IsRequired()
                        .HasConstraintName("FK__job_tech___tech___656C112C");
                });

            modelBuilder.Entity("DevHub.Models.Admin", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("DevHub.Models.Application", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("DevHub.Models.Candidate", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Bookmarks");

                    b.Navigation("CandidateSkills");

                    b.Navigation("Cvs");

                    b.Navigation("Interviews");

                    b.Navigation("ReviewCompanies");
                });

            modelBuilder.Entity("DevHub.Models.CommonJobPosition", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("DevHub.Models.CommonTechnology", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("DevHub.Models.Cv", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("DevHub.Models.JobPost", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("DevHub.Models.PackageTransaction", b =>
                {
                    b.Navigation("CompanyPackageHistories");
                });

            modelBuilder.Entity("DevHub.Models.Promotion", b =>
                {
                    b.Navigation("PackageTransactions");
                });

            modelBuilder.Entity("DevHub.Models.Recruiter", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Interviews");

                    b.Navigation("PackageTransactions");

                    b.Navigation("CompanyPackageHistories");

                    b.Navigation("ReviewCompanies");
                });

            modelBuilder.Entity("DevHub.Models.CompanyPackageHistory", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("DevHub.Models.ServicePackage", b =>
                {
                    b.Navigation("PackageTransactions");

                    b.Navigation("CompanyPackageHistories");
                });

            modelBuilder.Entity("DevHub.Models.UserAccount", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Candidate");

                    b.Navigation("Recruiter");
                });
#pragma warning restore 612, 618
        }
    }
}
